version: "3.9"

services:
  keydb:
    container_name: keydb
    image: eqalpha/keydb
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
    - drs-network
  storage:
    container_name: storage
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - drs-network
    depends_on:
      - keydb

networks:
  drs-network:
    driver: bridge